steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/finance-tracker-frontend:$SHORT_SHA', './frontend']

images:
- 'gcr.io/$PROJECT_ID/finance-tracker-frontend:$SHORT_SHA'